//! Shared generators for the core test suites (port of `Helpers.scala` and
//! `decision/Generators.scala`).

#![allow(dead_code)]

use std::future::Future;

use edomata_core::{Decision, NonEmpty, ResponseD};
use proptest::prelude::*;

pub type Rejection = String;
pub type Event = i32;
pub type Dec<T> = Decision<Rejection, Event, T>;
pub type Sut = Dec<i64>;

/// A notification type used across suites.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct Notification(pub String);

pub fn block_on<F: Future>(fut: F) -> F::Output {
    futures::executor::block_on(fut)
}

/// A non-empty collection of 1 to 10 elements.
pub fn nec_of<T: std::fmt::Debug + Clone + 'static>(
    g: impl Strategy<Value = T> + 'static,
) -> BoxedStrategy<NonEmpty<T>> {
    prop::collection::vec(g, 1..=10)
        .prop_map(|v| NonEmpty::from_vec(v).expect("non-empty by construction"))
        .boxed()
}

pub fn rejection() -> BoxedStrategy<Rejection> {
    "[a-z]{0,8}".boxed()
}

pub fn notification() -> BoxedStrategy<Notification> {
    "[a-z]{0,8}".prop_map(Notification).boxed()
}

pub fn notifications() -> BoxedStrategy<Vec<Notification>> {
    prop::collection::vec(notification(), 0..=6).boxed()
}

pub fn accepted() -> BoxedStrategy<Sut> {
    (any::<i64>(), nec_of(any::<Event>()))
        .prop_map(|(v, l)| Decision::Accepted {
            events: l,
            result: v,
        })
        .boxed()
}

pub fn rejected() -> BoxedStrategy<Sut> {
    nec_of(rejection()).prop_map(Decision::Rejected).boxed()
}

pub fn indecisive() -> BoxedStrategy<Sut> {
    any::<i64>().prop_map(Decision::InDecisive).boxed()
}

pub fn any_sut() -> BoxedStrategy<Sut> {
    prop_oneof![accepted(), rejected(), indecisive()].boxed()
}

pub fn not_rejected() -> BoxedStrategy<Sut> {
    prop_oneof![accepted(), indecisive()].boxed()
}

/// A decision whose output is generated by `g` (port of `Generators.decision`).
pub fn decision<T: std::fmt::Debug + Clone + 'static>(
    g: impl Strategy<Value = T> + Clone + 'static,
) -> BoxedStrategy<Dec<T>> {
    let ind = g.clone().prop_map(Decision::pure).boxed();
    prop_oneof![
        (accepted(), g.prop_map(Decision::pure)).prop_map(|(a, d)| a.then(d)),
        ind,
        rejected().prop_map(|r| r.map(|_: i64| unreachable!())),
    ]
    .boxed()
}

pub fn any_response() -> BoxedStrategy<ResponseD<Rejection, Event, Notification, i64>> {
    (any_sut(), notifications())
        .prop_map(|(d, ns)| ResponseD::new(d, ns))
        .boxed()
}

/// A deterministic "arbitrary function" `i64 -> Dec<i64>`, built from a
/// generated decision template and multiplier. Used for monad law tests in
/// place of ScalaCheck's `Cogen`-based function generators.
#[derive(Clone, Debug)]
pub struct DecFn {
    template: Sut,
    k: i64,
}

impl DecFn {
    pub fn call(&self, a: i64) -> Sut {
        let k = self.k;
        self.template
            .clone()
            .map(|v| v.wrapping_add(a).wrapping_mul(k))
    }
}

pub fn dec_fn() -> BoxedStrategy<DecFn> {
    (any_sut(), any::<i64>())
        .prop_map(|(template, k)| DecFn { template, k })
        .boxed()
}

/// A deterministic "arbitrary function" `i64 -> i64`.
#[derive(Clone, Copy, Debug)]
pub struct IntFn {
    add: i64,
    mul: i64,
}

impl IntFn {
    pub fn call(&self, a: i64) -> i64 {
        a.wrapping_mul(self.mul).wrapping_add(self.add)
    }
}

pub fn int_fn() -> BoxedStrategy<IntFn> {
    (any::<i64>(), any::<i64>())
        .prop_map(|(add, mul)| IntFn { add, mul })
        .boxed()
}
