pull_request_rules:
  - name: Automatic merge for dependency updates
    conditions:
      - "head~=update/"
      - or:
        - "author=hnaderi"
        - "author=scala-steward"
    actions:
      merge:
        method: merge
