//! Port of `SaaSPGSchemaSuite.scala` (`TenantExtractorSuite` and
//! `SaaSPGSchemaSuite`), plus the golden DDL comparison against the files
//! generated by `modules/saas/src/test/scala/edomata/saas/GoldenSaaSDDL.scala`.

use std::path::PathBuf;

use edomata_saas::{
    CrudState, PGNaming, RlsConfig, SaaSPGSchema, TenantExtractor, TenantId, UserId,
};

fn prefixed(ns: &str) -> PGNaming {
    PGNaming::prefixed_str(ns).unwrap()
}

fn schema(ns: &str) -> PGNaming {
    PGNaming::schema_str(ns).unwrap()
}

// --- TenantExtractorSuite ---------------------------------------------------

#[test]
fn extracts_tenant_and_owner_from_active_state() {
    let state = CrudState::active("t1", "u1", "data");
    assert_eq!(
        state.tenant_and_owner(),
        Some((TenantId::new("t1"), UserId::new("u1")))
    );
}

#[test]
fn extracts_tenant_and_owner_from_deleted_state() {
    let state: CrudState<String> = CrudState::deleted("t1", "u1");
    assert_eq!(
        state.tenant_and_owner(),
        Some((TenantId::new("t1"), UserId::new("u1")))
    );
}

#[test]
fn returns_none_for_non_existent_state() {
    let state: CrudState<String> = CrudState::NonExistent;
    assert_eq!(state.tenant_and_owner(), None);
}

// --- SaaSPGSchemaSuite ------------------------------------------------------

#[test]
fn cqrs_ddl_prefix_mode_contains_tenant_and_owner_in_states() {
    let all = SaaSPGSchema::cqrs(&prefixed("catalog")).join("\n");
    assert!(all.contains("catalog_states"));
    assert!(all.contains("tenant_id text NOT NULL"));
    assert!(all.contains("owner_id text NOT NULL"));
}

#[test]
fn cqrs_ddl_creates_states_with_tenant_indexes() {
    let all = SaaSPGSchema::cqrs(&prefixed("catalog")).join("\n");
    assert!(all.contains("catalog_states_tenant_idx"));
    assert!(all.contains("catalog_states_tenant_owner_idx"));
}

#[test]
fn cqrs_ddl_creates_outbox_with_tenant_column_and_index() {
    let ddl = SaaSPGSchema::cqrs(&prefixed("catalog"));
    let all = ddl.join("\n");
    assert!(all.contains("catalog_outbox"));
    assert!(all.contains("catalog_outbox_tenant_idx"));
    let outbox = ddl
        .iter()
        .find(|s| s.contains("catalog_outbox") && s.contains("CREATE TABLE"))
        .unwrap();
    assert!(outbox.contains("tenant_id text NOT NULL"));
}

#[test]
fn cqrs_ddl_creates_commands_table_without_tenant_id() {
    let ddl = SaaSPGSchema::cqrs(&prefixed("catalog"));
    let cmd = ddl
        .iter()
        .find(|s| s.contains("catalog_commands") && s.contains("CREATE TABLE"))
        .unwrap();
    assert!(!cmd.contains("tenant_id"));
}

#[test]
fn cqrs_ddl_schema_mode_includes_create_schema() {
    let ddl = SaaSPGSchema::cqrs(&schema("catalog"));
    assert!(ddl[0].contains("CREATE SCHEMA IF NOT EXISTS \"catalog\""));
}

#[test]
fn cqrs_ddl_prefix_mode_omits_create_schema() {
    let ddl = SaaSPGSchema::cqrs(&prefixed("catalog"));
    assert!(ddl.iter().all(|s| !s.contains("CREATE SCHEMA")));
}

#[test]
fn cqrs_ddl_respects_custom_payload_types() {
    let all = SaaSPGSchema::cqrs_with(&prefixed("app"), "bytea", "json", None).join("\n");
    assert!(all.contains("state bytea NOT NULL"));
    assert!(all.contains("payload json NOT NULL"));
}

#[test]
fn cqrs_ddl_without_rls_produces_no_alter_table_or_policy() {
    let all = SaaSPGSchema::cqrs_with(&prefixed("app"), "jsonb", "jsonb", None).join("\n");
    assert!(!all.contains("ROW LEVEL SECURITY"));
    assert!(!all.contains("CREATE POLICY"));
}

#[test]
fn cqrs_ddl_with_rls_produces_alter_table_policy_and_grant() {
    let rls = RlsConfig::new("app_user", "app.tenant_id");
    let all = SaaSPGSchema::cqrs_with(&prefixed("app"), "jsonb", "jsonb", Some(&rls)).join("\n");
    assert!(all.contains("ALTER TABLE app_states ENABLE ROW LEVEL SECURITY"));
    assert!(all.contains("CREATE POLICY app_states_tenant_policy ON app_states"));
    assert!(all.contains("current_setting('app.tenant_id')"));
    assert!(all.contains("GRANT SELECT, INSERT, UPDATE ON app_states TO app_user"));
    assert!(all.contains("ALTER TABLE app_outbox ENABLE ROW LEVEL SECURITY"));
}

#[test]
fn all_ddl_statements_end_with_semicolons() {
    for stmt in SaaSPGSchema::cqrs(&prefixed("test")) {
        assert!(
            stmt.ends_with(';'),
            "Statement does not end with semicolon: {stmt}"
        );
    }
}

// --- Golden files -----------------------------------------------------------

/// Must stay in sync with `GoldenSaaSDDL.scala`.
const NAMINGS: [(&str, &str); 3] = [
    ("schema", "catalog"),
    ("prefixed", "catalog"),
    ("schema", "Shop_v2$"),
];
const TYPES: [(&str, &str, &str); 4] = [
    ("jsonb", "jsonb", "jsonb"),
    ("json", "json", "json"),
    ("bytea", "bytea", "bytea"),
    ("mixed", "bytea", "json"),
];

fn golden_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../tests/golden")
}

#[test]
fn saas_ddl_matches_scala_golden_files() {
    let rls_config = RlsConfig::new("app_user", "app.tenant_id");
    let rls_cases: [(&str, Option<&RlsConfig>); 2] = [("norls", None), ("rls", Some(&rls_config))];
    let mut checked = 0;
    for (kind, ns) in NAMINGS {
        let naming = match kind {
            "schema" => schema(ns),
            "prefixed" => prefixed(ns),
            other => panic!("unknown naming {other}"),
        };
        for (label, state_type, notif_type) in TYPES {
            for (rls_label, rls) in rls_cases {
                let file = format!(
                    "saas_cqrs_{kind}_{}_{label}_{rls_label}.sql",
                    ns.to_lowercase().replace('$', "_")
                );
                let path = golden_dir().join(&file);
                let expected = std::fs::read_to_string(&path)
                    .unwrap_or_else(|e| panic!("missing golden file {}: {e}", path.display()));
                let actual =
                    SaaSPGSchema::cqrs_with(&naming, state_type, notif_type, rls).join("\n") + "\n";
                assert_eq!(actual, expected, "golden mismatch for {file}");
                checked += 1;
            }
        }
    }
    assert_eq!(checked, 24);
}

#[test]
fn every_saas_golden_file_is_covered() {
    let mut files: Vec<String> = std::fs::read_dir(golden_dir())
        .unwrap()
        .map(|e| e.unwrap().file_name().to_string_lossy().into_owned())
        .filter(|n| n.starts_with("saas_cqrs_"))
        .collect();
    files.sort();
    assert_eq!(files.len(), 24, "{files:?}");
}
