#!/usr/bin/env python3
"""Checks the Edomata for Rust book: run from `rust/` after `mdbook build book`.

- every `{{#include path:anchor}}` of `book/src` names an existing file and,
  when an anchor is given, a non-empty `ANCHOR: name` ... `ANCHOR_END: name`
  region of it;
- every relative link of the rendered HTML (`book/book`) points to an
  existing file, and every `#fragment` to an existing `id` of its target.

External links (`http:`, `https:`, `mailto:`) are not fetched. Exits with
status 1 and lists the problems when there is any.
"""

import html.parser
import pathlib
import re
import sys
import urllib.parse

ROOT = pathlib.Path(__file__).resolve().parent
SRC = ROOT / "src"
OUT = ROOT / "book"

INCLUDE = re.compile(r"\{\{#include\s+([^}\s]+)\s*\}\}")


def check_includes(problems):
    for md in sorted(SRC.rglob("*.md")):
        for match in INCLUDE.finditer(md.read_text(encoding="utf-8")):
            target, _, anchor = match.group(1).partition(":")
            path = (md.parent / target).resolve()
            where = f"{md.relative_to(ROOT)}: {match.group(0)}"
            if not path.is_file():
                problems.append(f"{where}: missing file {target}")
                continue
            if not anchor:
                continue
            lines = path.read_text(encoding="utf-8").splitlines()
            start = [i for i, l in enumerate(lines) if re.search(rf"ANCHOR:\s*{re.escape(anchor)}\s*$", l)]
            end = [i for i, l in enumerate(lines) if re.search(rf"ANCHOR_END:\s*{re.escape(anchor)}\s*$", l)]
            if len(start) != 1 or len(end) != 1 or end[0] <= start[0] + 1:
                problems.append(f"{where}: anchor '{anchor}' not found exactly once, or empty")


class Page(html.parser.HTMLParser):
    def __init__(self):
        super().__init__()
        self.ids = set()
        self.links = []

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        if attrs.get("id"):
            self.ids.add(attrs["id"])
        if tag == "a" and attrs.get("name"):
            self.ids.add(attrs["name"])
        if tag == "a" and attrs.get("href"):
            self.links.append(attrs["href"])


def check_links(problems):
    pages = {}
    for page in OUT.rglob("*.html"):
        parser = Page()
        parser.feed(page.read_text(encoding="utf-8"))
        pages[page.resolve()] = parser
    # Pages generated by mdBook itself, not from the sources.
    generated = {"print.html", "toc.html", "404.html"}
    for page, parser in sorted(pages.items()):
        if page.name in generated:
            continue
        for href in parser.links:
            url = urllib.parse.urlsplit(href)
            if url.scheme or href.startswith("//"):
                continue
            target = (page.parent / urllib.parse.unquote(url.path)).resolve() if url.path else page
            if target.is_dir():
                target = target / "index.html"
            where = f"{page.relative_to(OUT)}: {href}"
            if not target.exists():
                problems.append(f"{where}: missing target")
                continue
            if url.fragment and target.suffix == ".html":
                ids = pages[target].ids if target in pages else set()
                if urllib.parse.unquote(url.fragment) not in ids:
                    problems.append(f"{where}: missing anchor #{url.fragment}")


def main():
    if not OUT.is_dir():
        sys.exit("book/book not found: run `mdbook build book` first")
    problems = []
    check_includes(problems)
    check_links(problems)
    for problem in problems:
        print(problem)
    if problems:
        sys.exit(1)
    print("book: every include, anchor and relative link resolves")


if __name__ == "__main__":
    main()
