name: Publish to Maven Central

on:
  push:
    tags: ['v*']

concurrency:
  group: publish
  cancel-in-progress: false

jobs:
  test:
    name: Test (${{ matrix.project }})
    strategy:
      matrix:
        os: [ubuntu-22.04]
        java: [temurin@8]
        project: [rootJVM, rootJS, rootNative]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Start up Postgres
        run: docker compose up -d

      - name: Build and test
        run: >-
          nix develop .#${{ matrix.java }} -c sbt
          'project ${{ matrix.project }}'
          '++ 3'
          test

  publish:
    name: Publish all platforms
    needs: [test]
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Import PGP key
        run: echo "$PGP_SECRET" | base64 -d | gpg --import --batch --yes
        env:
          PGP_SECRET: ${{ secrets.PGP_SECRET }}

      - name: Publish to Maven Central
        run: >-
          nix develop .#temurin@8 -c sbt
          '++ 3'
          tlRelease
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_USERNAME: ${{ secrets.OSS_SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
